---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: reduce-snapshot
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to reduce snapshot
  params:
    - name: SNAPSHOT
      type: string
      description: String representation of Snapshot spec
    - name: SINGLE_COMPONENT
      type: string
      description: Single mode component enabled
    - name: SINGLE_COMPONENT_CUSTOM_RESOURCE
      type: string
      description: Custom Resource to query for built component in Snapshot
    - name: SINGLE_COMPONENT_CUSTOM_RESOURCE_NS
      type: string
      default: ""
      description: Namespace where Custom Resource is found
    - name: SNAPSHOT_PATH
      type: string
      description: The location to place the reduced Snapshot
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: "1d"
    - name: sourceDataArtifact
      type: string
    - name: subdirectory
      description: Subdirectory inside the workspace to be used
      type: string
      default: ""
  results:
    - description: Produced trusted data artifact
      name: sourceDataArtifact
      type: string
  workspaces:
    - name: data
      description: Workspace to save the CR jsons to
  steps:
    - name: skip-trusted-artifact-operations
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -eo pipefail

        if [ "$(params.ociStorage)" == "empty" ]; then
          echo "oci storage not detected via params.ociStorage ... skipping trusted artifacts tasks"
          touch "$(workspaces.data.path)/$(params.subdirectory)/.skip-trusted-artifacts"
        fi
    - name: use-trusted-artifact
      args:
        - use
        - $(params.sourceDataArtifact)=$(workspaces.data.path)/$(params.subdirectory)
      env:
        - name: "ORAS_OPTIONS"
          value: "--insecure"
        - name: "HOME"
          value: "/tekton/home"
      computeResources: {}
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
    - name: reduce
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: SINGLE_COMPONENT
          value: $(params.SINGLE_COMPONENT)
        - name: CUSTOM_RESOURCE
          value: $(params.SINGLE_COMPONENT_CUSTOM_RESOURCE)
        - name: CUSTOM_RESOURCE_NAMESPACE
          value: $(params.SINGLE_COMPONENT_CUSTOM_RESOURCE_NS)
        - name: SNAPSHOT_PATH
          value: $(params.SNAPSHOT_PATH)
      image: quay.io/enterprise-contract/ec-cli@sha256:913c7dac3d41877b01835d2e55bcd970c6cdbf4944f8176e9e3de9548642a2b4
      command: [reduce-snapshot.sh]
      onError: continue  # progress even if the step fails
    - name: create-trusted-artifact
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.sourceDataArtifact.path)=$(workspaces.data.path)/$(params.subdirectory)
      computeResources: {}
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
      env:
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.ociArtifactExpiresAfter)
        - name: "ORAS_OPTIONS"
          value: "--insecure"
        - name: "HOME"
          value: "/tekton/home"
    - name: patch-source-data-artifact-result
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -eu

        # this is needed to skip trusted-artifacts tasks
        # when using PVC based workspaces.
        if [ "$(params.ociStorage)" == "empty" ]; then
          echo -n "$(params.ociStorage)" > "$(results.sourceDataArtifact.path)"
        fi
