---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: reduce-snapshot
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to reduce snapshot
  params:
    - name: SNAPSHOT
      type: string
      description: String representation of Snapshot spec
    - name: SINGLE_COMPONENT
      type: string
      description: Single mode component enabled
    - name: SINGLE_COMPONENT_CUSTOM_RESOURCE
      type: string
      description: Custom Resource to query for built component in Snapshot
    - name: SINGLE_COMPONENT_CUSTOM_RESOURCE_NS
      type: string
      default: ""
      description: Namespace where Custom Resource is found
    - name: SNAPSHOT_PATH
      type: string
      description: The location to place the reduced Snapshot
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: "1d"
    - name: SOURCE_DATA_ARTIFACT
      type: string
  results:
    - description: Produced trusted data artifact
      name: SOURCE_DATA_ARTIFACT
      type: string
  workspaces:
    - name: data
      description: Workspace to save the CR jsons to
  steps:
    - name: use-trusted-artifact
      args:
        - use
        - $(params.SOURCE_DATA_ARTIFACT)=$(workspaces.data.path)
      env:
        - name: "ORAS_OPTIONS"
          value: "--insecure"
      computeResources: {}
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
    - name: reduce
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: SINGLE_COMPONENT
          value: $(params.SINGLE_COMPONENT)
        - name: CUSTOM_RESOURCE
          value: $(params.SINGLE_COMPONENT_CUSTOM_RESOURCE)
        - name: CUSTOM_RESOURCE_NAMESPACE
          value: $(params.SINGLE_COMPONENT_CUSTOM_RESOURCE_NS)
        - name: SNAPSHOT_PATH
          value: $(params.SNAPSHOT_PATH)
      image: quay.io/enterprise-contract/ec-cli@sha256:913c7dac3d41877b01835d2e55bcd970c6cdbf4944f8176e9e3de9548642a2b4
      command: [reduce-snapshot.sh]
      onError: continue  # progress even if the step fails
    - name: create-trusted-artifact
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.SOURCE_DATA_ARTIFACT.path)=$(workspaces.data.path)
      computeResources: {}
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
      env:
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.ociArtifactExpiresAfter)
        - name: "ORAS_OPTIONS"
          value: "--insecure"
