---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${managed_namespace}
resources:
  - sa.yaml
  - sa-rolebinding.yaml
  - rpa.yaml
  - ec-policy.yaml
  - secrets/managed-secrets.yaml
