---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: use-trusted-artifact-array
spec:
  description: >-
    This stepaction extracts an array of Trusted Artifacts into a folder.
  image: quay.io/redhat-appstudio/build-trusted-artifacts:e02102ede09aa07187cba066ad547a54724e5cf4
  env:
    # Set HOME variable to something else than `/` to avoid 'permission denied' problems when writing files.
    - name: HOME
      value: /tekton/home
  params:
    - name: sourceDataArtifacts
      type: array
      description: Array of artifacts to extract
      default: []
  args:
    - use
    - "$(params.sourceDataArtifacts[*])"
