---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-snapshot
  labels:
    app.kubernetes.io/version: "6.5.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to push snapshot images to an image registry using `cosign copy`
  params:
    - name: snapshotPath
      description: Path to the JSON string of the mapped Snapshot spec in the data workspace
      type: string
    - name: dataPath
      description: Path to the JSON string of the merged data to use in the data workspace
      type: string
    - name: resultsDirPath
      description: Path to the results directory in the data workspace
      type: string
    - name: retries
      description: Retry copy N times.
      type: string
      default: "0"
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from.
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data.
      default: ca-bundle.crt
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: "1d"
    - name: sourceDataArtifact
      type: string
    - name: subdirectory
      description: Subdirectory inside the workspace to be used
      type: string
      default: ""
  results:
    - description: Produced trusted data artifact
      name: sourceDataArtifact
      type: string
  workspaces:
    - name: data
      description: The workspace where the snapshot spec and data json files reside
  steps:
    - name: skip-trusted-artifact-operations
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -eo pipefail

        if [ "$(params.ociStorage)" == "empty" ]; then
          echo "oci storage not detected via params.ociStorage ... skipping trusted artifacts tasks"
          touch "$(workspaces.data.path)/$(params.subdirectory)/.skip-trusted-artifacts"
        fi
    - name: use-trusted-artifact
      args:
        - use
        - $(params.sourceDataArtifact)=$(workspaces.data.path)/$(params.subdirectory)
      env:
        - name: "ORAS_OPTIONS"
          value: "--insecure"
        - name: "HOME"
          value: "/tekton/home"
      computeResources: {}
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
    - name: push-snapshot
      image: quay.io/konflux-ci/release-service-utils:066a63d25546239e79533b99c83ff521a045c819
      script: |
        #!/usr/bin/env bash
        set -eux

        push_image () { # Expected arguments are [origin_digest, name, containerImage, repository, tag, platform]
          # note: Inspection might fail on empty repos, hence `|| true`

          # oras has very limited support for selecting the right auth entry,
          # so create a custom auth file with just one entry.
          DEST_AUTH_FILE=$(mktemp)
          registry=$(echo "$4" | cut -d '/' -f 1)
          if [ "$registry" = "docker.io" ]; then
            # For docker.io, the auth key will always be https://index.docker.io/v1/
            select-oci-auth "$4" > "$DEST_AUTH_FILE"
          else
            # For other registries, the auth key will be modified to the full repository path, so that
            # we can create a combined auth file with source and destination entries for `cosign copy` later
            select-oci-auth "$4" | jq -c \
              '.auths."'"$4"'" = .auths."'"$registry"'" | del(.auths."'"$registry"'")' > "$DEST_AUTH_FILE"
          fi

          oras_args=()
          if [ -n "$6" ]; then
            oras_args=(--platform "$6")
          fi

          destination_digest=$(oras resolve --registry-config "$DEST_AUTH_FILE" "${oras_args[@]}" "$4:$5" || true)

          if [[ "$destination_digest" != "$1" || -z "$destination_digest" ]]; then
            printf '* Pushing component: %s to %s:%s\n' "$2" "$4" "$5"
            # Create a combined auth file to enable partial oci matches to work
            DOCKER_CONFIG="$(mktemp -d)"
            export DOCKER_CONFIG
            # shellcheck disable=SC2128
            jq -s 'reduce .[] as $item ({}; . * $item)' \
              "$SOURCE_AUTH_FILE" "$DEST_AUTH_FILE" > "$DOCKER_CONFIG"/config.json
            attempt=0
            until [ "$attempt" -gt "$(params.retries)" ] ; do # 0 retries by default which will execute this once
              cosign copy -f "$3" "$4:$5" && break
              attempt=$((attempt+1))
            done
            if [ "$attempt" -gt "$(params.retries)" ] ; then
              echo "Max retries exceeded."
              exit 1
            fi
            # Only the cosign call above needs this custom Docker config. Unset it, so that skopeo call
            # in get-image-architecture uses the default config in ~/.docker/config.json (this one would break it)
            unset DOCKER_CONFIG
          else
            printf '* Component push skipped (source digest exists at destination): %s (%s)\n' \
              "$2" "$3"
          fi
          RESULTS_JSON=$(jq --arg name "$2" --arg url "$4:$5" '.images |= map(select(.name==$name).urls +=
            [$url])' <<< "$RESULTS_JSON")
        }

        SNAPSHOT_SPEC_FILE="$(workspaces.data.path)/$(params.snapshotPath)"
        if [ ! -f "${SNAPSHOT_SPEC_FILE}" ] ; then
            echo "No valid snapshot file was provided."
            exit 1
        fi

        DATA_FILE="$(workspaces.data.path)/$(params.dataPath)"
        if [ ! -f "${DATA_FILE}" ] ; then
            echo "No data JSON was provided."
            exit 1
        fi

        if [ "$(jq '.components | map(select((has("tags")|not) or (.tags | IN([])))) | length' \
          "${SNAPSHOT_SPEC_FILE}")" -ne 0 ] ; then
            echo "Found components in the snapshot file that do not contain tags. Failing"
            cat "${SNAPSHOT_SPEC_FILE}"
            exit 1
        fi

        RESULTS_FILE="$(workspaces.data.path)/$(params.resultsDirPath)/push-snapshot-results.json"
        RESULTS_JSON="{\"images\":[]}"
        SOURCE_AUTH_FILE=$(mktemp)

        defaultPushSourceContainer=$(jq -r '.mapping.defaults.pushSourceContainer' "$DATA_FILE")

        application=$(jq -r '.application' "${SNAPSHOT_SPEC_FILE}")
        NUM_COMPONENTS=$(jq '.components | length' "${SNAPSHOT_SPEC_FILE}")
        printf 'Beginning "%s" for "%s"\n\n' "$(context.task.name)" "$application"
        for ((i = 0; i < NUM_COMPONENTS; i++))
        do
          component=$(jq -c --argjson i "$i" '.components[$i]' "${SNAPSHOT_SPEC_FILE}")
          containerImage=$(jq -r '.containerImage' <<< "$component")
          repository=$(jq -r '.repository' <<< "$component")
          imageTags=$(jq '.tags' <<< "$component")

          # oras has very limited support for selecting the right auth entry,
          # so create a custom auth file with just one entry.
          registry=$(echo "${containerImage}" | cut -d '/' -f 1)
          # Apply-mapping ensures that the containerImage contains a sha256 digest
          source_repo=${containerImage%%@sha256:*}
          select-oci-auth "${containerImage}" | jq -c \
            '.auths."'"$source_repo"'" = .auths."'"$registry"'" | del(.auths."'"$registry"'")' > "$SOURCE_AUTH_FILE"

          arch_json=$(get-image-architectures "${containerImage}")
          arches=$(jq -s 'map(.platform.architecture)' <<< "$arch_json")
          oses=$(jq -s 'map(.platform.os)' <<< "$arch_json")

          # Just read the first from the list of architectures
          os=$(jq -r '.[0]' <<< "$oses")
          arch=$(jq -r '.[0]' <<< "$arches")
          name=$(jq -r '.name' <<< "$component")
          media_type=$(skopeo inspect --raw "docker://${containerImage}" | jq -r .mediaType)
          oras_args=()
          platform=
          if [[ "$media_type" == "application/vnd.docker.distribution.manifest.list.v2+json" ]]\
            || [[ "$media_type" == "application/vnd.oci.image.index.v1+json" ]]; then
            platform=$os/$arch
            oras_args=(--platform "$platform")
          fi

          # we do not use oras_args here since we want to get the manifest index image digest
          origin_digest=$(oras resolve --registry-config "$SOURCE_AUTH_FILE" "${containerImage}")

          RESULTS_JSON=$(jq --arg i "$i" --argjson arches "$arches" --argjson oses "$oses" --arg name "$name" \
            --arg sha "$origin_digest" \
            '.images[$i|tonumber] += {"arches": $arches, "oses": $oses, "name": $name, "shasum": $sha, "urls": []}' \
              <<< "$RESULTS_JSON")

          # Push source container if the component has pushSourceContainer: true or if the
          # pushSourceContainer key is missing from the component and the defaults has
          # pushSourceContainer: true
          if [[ $(jq -r '.pushSourceContainer' <<< "$component") == "true" ]] \
            || [[ $(jq 'has("pushSourceContainer")' <<< "$component") == "false" && \
                  ${defaultPushSourceContainer} == "true" ]] ; then

            source_tag=${origin_digest/:/-}.src
            # Calculate the source container image based on the provided container image
            sourceContainer="${source_repo}:${source_tag}"
            # Check if the source container exists
            source_container_digest=$(oras resolve --registry-config "$SOURCE_AUTH_FILE" \
              "${sourceContainer}")

            if [ -z "$source_container_digest" ] ; then
              echo "Error: Source container ${sourceContainer} not found!"
              exit 1
            fi
            # Push the source image with the source tag here. The source image will be
            # pushed with the provided tags below in the loop
            push_image "${source_container_digest}" "${name}" "${sourceContainer}" \
              "${repository}" "${source_tag}" ""
          fi

          for tag in $(jq -r '.[]' <<< "$imageTags") ; do
            # Push the container image
            push_image "${origin_digest}" "${name}" "${containerImage}" "${repository}" "${tag}" \
            "$platform"

            # This variable will only exist if the above logic determined the source container should
            # be pushed for this component
            if [ -n "${source_container_digest-}" ] ; then
              push_image "${source_container_digest}" "${name}" "${sourceContainer}" \
                "${repository}" "${tag}-source" ""
            fi
          done
        done
        echo -n "${RESULTS_JSON}" | tee "$RESULTS_FILE"
        printf 'Completed "%s" for "%s"\n\n' "$(context.task.name)" "$application"
      volumeMounts:
        - name: trusted-ca
          mountPath: /etc/ssl/certs/ca-custom-bundle.crt
          subPath: ca-bundle.crt
          readOnly: true
    - name: create-trusted-artifact
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.sourceDataArtifact.path)=$(workspaces.data.path)/$(params.subdirectory)
      computeResources: {}
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
      env:
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.ociArtifactExpiresAfter)
        - name: "ORAS_OPTIONS"
          value: "--insecure"
        - name: "HOME"
          value: "/tekton/home"
    - name: patch-source-data-artifact-result
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -eu

        # this is needed to skip trusted-artifacts tasks
        # when using PVC based workspaces.
        if [ "$(params.ociStorage)" == "empty" ]; then
          echo -n "$(params.ociStorage)" > "$(results.sourceDataArtifact.path)"
        fi
  volumes:
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
