---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  data:
    cdn:
      env: stage
    mapping:
      components:
        - name: ${component_name}
          files:
            - filename: releng-test-product-binaries-windows-amd64.gz
              source: /releases/releng-test-product-binaries-windows-amd64.gz
              arch: amd64
              os: windows
            - filename: releng-test-product-binaries-linux-amd64.gz
              source: /releases/releng-test-product-binaries-linux-amd64.gz
              arch: amd64
              os: linux
            - filename: releng-test-product-binaries-darwin-amd64.gz
              source: /releases/releng-test-product-binaries-darwin-amd64.gz
              arch: amd64
              os: darwin
            - filename: releng-test-product-binaries-linux-arm64.gz
              source: /releases/releng-test-product-binaries-linux-arm64.gz
              arch: arm64
              os: linux
            - filename: releng-test-product-binaries-darwin-arm64.gz
              source: /releases/releng-test-product-binaries-darwin-arm64.gz
              arch: arm64
              os: darwin
          contentGateway:
              productName: "Releng Test Product"
              productCode: "RelengTestProduct"
              productVersionName: "1.5.0"
              filePrefix: "releng-test-product-binaries"
              contentType: "binary"
    releaseNotes:
      product_id:
        - 999
      product_name: Red Hat Comp2
      product_version: '1.0.1'
      cpe: 'cpe:/a:redhat:comp2:1::appstream'
      product_stream: comp2-1.0
      synopsis: "Releng Test Product"
      description: "Releng Test Product"
      solution: "Releng Test Product"
      topic: "Releng Test Product"
    intention: production
    atlas:
      server: stage
      atlas-sso-secret-name: atlas-staging-sso-secret-${component_name}
      atlas-retry-aws-secret-name: atlas-retry-s3-staging-secret-${component_name}
    pyxis:
      server: stage
      secret: pyxis-${component_name}
      skipLayers: true
    sign:
      configMapName: "${component_name}-config-staging-redhatbeta2"
      cosignSecretName: "konflux-cosign-signing-stage-${component_name}"
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/push-artifacts-to-cdn/push-artifacts-to-cdn.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
