---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-file-updates
  labels:
    app.kubernetes.io/version: "4.0.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to run file updates
  params:
    - name: jsonKey
      type: string
      description: The json key containing the file updates
      default: ".spec.data.fileUpdates"
    - name: fileUpdatesPath
      type: string
      description: The path to the file containing the file updates
    - name: snapshotPath
      type: string
      description: Path to the JSON string of the Snapshot spec in the data workspace
    - name: request
      type: string
      description: Name of the request
      default: "process-file-updates"
    - name: requestTimeout
      type: string
      default: "900"
      description: InternalRequest timeout
    - name: synchronously
      type: string
      description: Whether to run synchronously or not
      default: "true"
    - name: pipelineRunUid
      type: string
      description: The uid of the current pipelineRun. Used as a label value when creating internal requests
    - name: resultsDirPath
      description: Path to the results directory in the data workspace
      type: string
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
      default: "empty"
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: "1d"
    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable.
      type: string
      default: ""
    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""
    - name: sourceDataArtifact
      type: string
      default: ""
    - name: subdirectory
      description: Subdirectory inside the workspace to be used
      type: string
      default: ""
    - name: dataDir
      description: The location where data will be stored
      type: string
      default: $(workspaces.data.path)
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks and stepactions to be used are stored
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
  results:
    - name: mergeRequestUrl
      description: URL of MR that was created
    - description: Produced trusted data artifact
      name: sourceDataArtifact
      type: string
  workspaces:
    - name: data
      description: Workspace where the file updates to apply are defined
  volumes:
    - name: workdir
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"
  steps:
    - name: skip-trusted-artifact-operations
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/skip-trusted-artifact-operations/skip-trusted-artifact-operations.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)/$(params.subdirectory)
    - name: use-trusted-artifact
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)/$(params.subdirectory)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)
    - name: run-script
      image: quay.io/konflux-ci/release-service-utils:0f82be4be43294b6a96846d87ef7f7c0b9e34267
      onError: continue
      script: |
        #!/bin/bash
        #
        #
        set -ex

        # shellcheck disable=SC2317 # shellcheck calls all the commands in exitfunc unreachable because it is called
        # via trap
        exitfunc() {
            local err="$1"
            local line="$2"
            local command="$3"
            if [ "$err" -ne 0 ] ; then
                echo -n \
                  "$0: ERROR '$command' failed at line $line - exited with status $err"
                touch "$(params.dataDir)/$(params.subdirectory)/error"
            fi
            exit 0
        }
        # due to set -e, this catches all EXIT and ERR calls and the task should never fail with nonzero exit code
        trap 'exitfunc $? $LINENO "$BASH_COMMAND"' EXIT

        rm -rf "$(params.dataDir)/$(params.subdirectory)/error"
        
        # Obtain application from snapshot
        application=$(jq -rc .application "$(params.dataDir)/$(params.snapshotPath)")

        # Extract the key from the JSON file
        fileUpdates=$(jq -rc "$(params.jsonKey)" "$(params.dataDir)/$(params.fileUpdatesPath)")

        TASK_LABEL="internal-services.appstudio.openshift.io/group-id"
        REQUEST_LABEL="internal-services.appstudio.openshift.io/request-id"
        TASK_ID=$(context.taskRun.uid)
        PIPELINERUN_LABEL="internal-services.appstudio.openshift.io/pipelinerun-uid"

        RESULTS_FILE="$(params.dataDir)/$(params.resultsDirPath)/file-updates-results.json"
        RESULTS_JSON='{"merge_requests":[]}'

        # empty result to start so result is available
        touch "$(results.mergeRequestUrl.path)"

        # Iterate over the extracted array and call the script
        fileUpdatesLength=$(jq '. | length' <<< "${fileUpdates}")
        for((i=0; i<fileUpdatesLength; i++)); do
          item=$(jq -cr ".[$i]" <<< "${fileUpdates}")

          repo=$(jq -r '.repo' <<< "${item}")
          upstream_repo=$(jq -r '.upstream_repo' <<< "${item}")
          ref=$(jq -r '.ref // "main"' <<< "${item}")
          paths=$(jq -cr '.paths // "[]"' <<< "${item}")
          file_updates_secret=$(jq -r '.file_updates_secret // "file-updates-secret"' <<< "${item}")

          echo "=== Updates for repo: ${repo} ==="

          echo -en "  Evaluating '{{ }}' expressions..."
          updatedPaths=$(update-paths -p "${paths}" -f "$(params.dataDir)/$(params.snapshotPath)")
          echo "done"

          echo -en "  Creating InternalRequest to produce file-updates..."
          requestId="$(openssl rand -hex 12)"
          internal-request --pipeline "$(params.request)" \
                           -p upstream_repo="${upstream_repo}" \
                           -p repo="${repo}" \
                           -p ref="${ref}" \
                           -p paths="${updatedPaths}" \
                           -p application="${application}" \
                           -p file_updates_secret="${file_updates_secret}" \
                           -p taskGitUrl="$(params.taskGitUrl)" \
                           -p taskGitRevision="$(params.taskGitRevision)" \
                           -s "$(params.synchronously)" \
                           -t "$(params.requestTimeout)" \
                           -l ${TASK_LABEL}="${TASK_ID}" \
                           -l ${REQUEST_LABEL}="${requestId}" \
                           -l "${PIPELINERUN_LABEL}=$(params.pipelineRunUid)"

          IRjson=$(kubectl get internalrequest \
            -l "${PIPELINERUN_LABEL}=$(params.pipelineRunUid),${TASK_LABEL}=${TASK_ID},${REQUEST_LABEL}=${requestId}" \
            -o jsonpath='{.items[0]}' --sort-by=.metadata.creationTimestamp )

          results=$(jq -r '.status.results' <<< "${IRjson}")
          internalRequestPipelineRunName="$(jq -jr '.internalRequestPipelineRunName // ""' <<< "${results}")"
          internalRequestTaskRunName="$(jq -jr '.internalRequestTaskRunName // ""' <<< "${results}")"

          echo "** internalRequestPipelineRunName: ${internalRequestPipelineRunName}"
          echo "** internalRequestTaskRunName: ${internalRequestTaskRunName}"

          if [ "$(jq -jr '.buildState' <<< "${results}")" == "Failed" ]; then
            echo -en "  FileUpdates Error: "
            jq -r '.jsonBuildInfo | fromjson | .error' <<< "${results}"
            echo -e "  Diff (content might be truncated): "
            jq -r '.jsonBuildInfo | fromjson | .str | tostring' <<< "${results}" | awk '{ print "\t"$0 }'
            echo -e "=== Finished ===\n"
            exit 1
          else
            MR=$(jq -r '.jsonBuildInfo | fromjson | .merge_request // "unknown"' <<< "${results}")
            echo "MR Created: ${MR}"
            echo "${MR}" >> "$(results.mergeRequestUrl.path)"
            RESULTS_JSON=$(jq --arg i "$i" --arg MR "${MR}" '.merge_requests[$i|tonumber] += {"url": $MR}' \
                <<< "$RESULTS_JSON")
            echo -n "${RESULTS_JSON}" | tee "$RESULTS_FILE"
          fi
          echo -e "=== Finished ===\n"
        done
    - name: create-trusted-artifact
      ref:
        resolver: "git"
        params:
          - name: url
            value: "$(params.taskGitUrl)"
          - name: revision
            value: "$(params.taskGitRevision)"
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)/$(params.subdirectory)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
    - name: patch-source-data-artifact-result
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/patch-source-data-artifact-result/patch-source-data-artifact-result.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
    - name: fail-on-error
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -eu

        if [ -f "$(params.dataDir)/$(params.subdirectory)/error" ]; then
          echo "Errors encountered"
          exit 1
        fi
