---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_happy_name}
  labels:
    originating-tool: "fbc-release-e2e-test"
spec:
  applications:
    - ${application_name}
  data:
    fbc:
      fromIndex: "registry-proxy.engineering.redhat.com/rh-osbs/iib-preview-rhtap:{{ OCP_VERSION }}"
      stagedIndex: false
      targetIndex: "quay.io/redhat/redhat----preview-operator-index:{{ OCP_VERSION }}"
      publishingCredentials: "fbc-preview-publishing-credentials"
      requestTimeoutSeconds: 1500
      buildTimeoutSeconds: 1500
      hotfix: false
      issueId: ""
      preGA: false
      productName: ""
      productVersion: ""
      allowedPackages:
        - "example-operator"
    sign:
      configMapName: "hacbs-signing-pipeline-config-redhatbeta2"
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/fbc-release/fbc-release.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_hotfix_name}
  labels:
    originating-tool: "fbc-release-e2e-test"
spec:
  applications:
    - ${application_name}
  data:
    fbc:
      fromIndex: "registry-proxy.engineering.redhat.com/rh-osbs/iib-preview-rhtap:{{ OCP_VERSION }}"
      stagedIndex: false
      targetIndex: "quay.io/redhat/redhat----preview-operator-index:{{ OCP_VERSION }}"
      publishingCredentials: "fbc-preview-publishing-credentials"
      requestTimeoutSeconds: 1500
      buildTimeoutSeconds: 1500
      hotfix: true
      issueId: "bz12345"
      preGA: false
      productName: ""
      productVersion: ""
      allowedPackages:
        - "example-operator"
    sign:
      configMapName: "hacbs-signing-pipeline-config-redhatbeta2"
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/fbc-release/fbc-release.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_prega_name}
  labels:
    originating-tool: "fbc-release-e2e-test"
spec:
  applications:
    - ${application_name}
  data:
    fbc:
      fromIndex: "registry-proxy.engineering.redhat.com/rh-osbs/iib-preview-rhtap:{{ OCP_VERSION }}"
      stagedIndex: false
      targetIndex: "quay.io/redhat/redhat----preview-operator-index:{{ OCP_VERSION }}"
      publishingCredentials: "fbc-preview-publishing-credentials"
      requestTimeoutSeconds: 1500
      buildTimeoutSeconds: 1500
      hotfix: false
      issueId: "bz12345"
      preGA: true
      productName: "preGA-product"
      productVersion: "v2"
      allowedPackages:
        - "example-operator"
    sign:
      configMapName: "hacbs-signing-pipeline-config-redhatbeta2"
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/fbc-release/fbc-release.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_staged_name}
  labels:
    originating-tool: "fbc-release-e2e-test"
spec:
  applications:
    - ${application_name}
  data:
    fbc:
      fromIndex: "registry-proxy.engineering.redhat.com/rh-osbs/iib-preview-rhtap:{{ OCP_VERSION }}"
      stagedIndex: true
      targetIndex: ""
      publishingCredentials: "fbc-preview-publishing-credentials"
      requestTimeoutSeconds: 1500
      buildTimeoutSeconds: 1500
      hotfix: false
      issueId: ""
      preGA: false
      productName: ""
      productVersion: ""
      allowedPackages:
        - "example-operator"
    sign:
      configMapName: "hacbs-signing-pipeline-config-redhatbeta2"
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/fbc-release/fbc-release.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
