---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-internal-requests
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to delete internal requests associated with a pipelinerun
  params:
    - name: pipelineRunUid
      type: string
      description: The uid of the current pipelineRun. It is only available at the pipeline level
  steps:
    - name: cleanup-internal-requests
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -eux

        if [ -n "$(params.pipelineRunUid)" ] ; then
            # Cleanup all internalrequests, but only if internalrequests exist on cluster
            if kubectl api-resources | grep InternalRequest | grep appstudio.redhat.com ; then
              kubectl delete internalrequest \
                  -l internal-services.appstudio.openshift.io/pipelinerun-uid="$(params.pipelineRunUid)"
            else
              echo "CRD internalrequests.appstudio.redhat.com not found on cluster"
            fi
        fi
