---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    git-provider: github
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
    build.appstudio.openshift.io/pipeline: '{"name": "docker-build-multi-platform-oci-ta", "bundle": "latest"}'
  name: ${component_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  application: ${application_name}
  componentName: ${component_name}
  secret: pipelines-as-code-secret-${component_name}
  source:
    git:
      dockerfileUrl: Dockerfile
      revision: ${component_branch}
      url: "${component_git_url}"
