---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
    release.appstudio.openshift.io/releasePlanAdmission: "${release_plan_admission_name}"
  name: ${release_plan_name}
spec:
  application: ${application_name}
  target: ${managed_namespace}
  data:
    releaseNotes:
      type: "RHBA"
      synopsis: |
        {% if advisory.spec.type == 'RHSA' %}Security Fix
        {% elif advisory.spec.type == 'RHBA' %}Bug Fix
        {% elif advisory.spec.type == 'RHEA' %}Enhancement
        {% else %}Unknown
        {% endif %}
      solution: |
        Use this great component.
      references:
        - "https://catalog.redhat.com/software/containers/search"
  tenantPipeline:
    serviceAccountName: ${tenant_sa_name}
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/seanconroy2021/sc-konflux-demos.git
        - name: revision
          value: main
        - name: pathInRepo
          value: RELEASE-1053/pipeline/pipeline.yaml
    params:
      - name: released_version
        value: 1.2.1
  collectors:
    items:
      - name: jira-collector
        params:
          - name: url
            value: https://issues.redhat.com
          - name: query
            value: 'project = "Konflux Release"  AND summary ~ "test issue for collector e2e testing"'
          - name: secretName
            value: "jira-collectors-secret-${component_name}"
        timeout: 60
        type: jira
      - name: cve
        params: []
        type: cve
      - name: convertyaml
        params:
          - name: git
            value: https://github.com/scoheb/e2e-base.git
          - name: branch
            value: convertyaml-test
          - name: path
            value: test.yaml
        type: convertyaml
    serviceAccountName: ${tenant_sa_name}
