---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  data:
    mapping:
      components:
        - name: ${component_name}
          repository: quay.io/hacbs-release-tests/osd-addons/e2e-component-index
          tags:
            - '{{ git_short_sha }}'
    targetGHRepo: 'hacbs-release/infra-deployments'
    githubAppID: 932323
    githubAppInstallationID: 52284535
    infra-deployment-update-script: "sed -i -e 's|\\(https://github.com/hacbs-release/release-service/config/default?ref=\\)\\(.*\\)|\\1{{ revision }}|' -e 's/\\(newTag: \\).*/\\1{{ revision }}/' components/release/development/kustomization.yaml"
    sign:
      configMapName: "hacbs-signing-pipeline-config-redhatbeta2"
    pyxis:
      server: stage
      secret: pyxis-${component_name}
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/rhtap-service-push/rhtap-service-push.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
