---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    git-provider: github
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
    build.appstudio.openshift.io/pipeline: '{"name": "fbc-builder", "bundle": "latest"}'
  name: ${component_name}
spec:
  application: ${application_name}
  componentName: ${component_name}
  secret: pipelines-as-code-secret-${component_name}
  source:
    git:
      dockerfileUrl: catalog.Dockerfile
      revision: ${component_branch}
      context: "4.13"
      url: "${component_git_url}"
