---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: skip-trusted-artifact-operations
spec:
  description: >-
    This stepaction creates the file .skip-trusted-artifacts if the param ociStorage is
    "empty".
  image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
  params:
    - name: ociStorage
      type: string
      default: "empty"
    - name: workDir
      type: string
      default: "/workspace/data"
  env:
    - name: ociStorage
      value: $(params.ociStorage)
    - name: workDir
      value: $(params.workDir)
  script: |
    #!/usr/bin/env bash
    set -eo pipefail

    if [ "${ociStorage:?}" == "empty" ]; then
      echo "oci storage not detected via ociStorage...skipping trusted artifacts tasks"
      mkdir -p "${workDir:?}"
    
      # Check if the skip file already exists to avoid permission issues
      if [ -f "${workDir:?}/.skip-trusted-artifacts" ]; then
        echo "Skip file already exists, continuing..."
      else
        # Try to create the file, handle permission issues gracefully
        if ! touch "${workDir:?}/.skip-trusted-artifacts" 2>/dev/null; then
          # If we can't create the file due to permissions, try to fix permissions
          if [ -d "${workDir:?}" ]; then
            # Try to make the directory writable by the current user
            chmod u+w "${workDir:?}" 2>/dev/null || true
            # Try again to create the file
            if ! touch "${workDir:?}/.skip-trusted-artifacts" 2>/dev/null; then
              echo "ERROR: Cannot create .skip-trusted-artifacts file due to permissions"
              echo "       This may cause issues with trusted artifacts operations"
              # Exit with error to surface the permission issue
              exit 1
            fi
          else
            echo "ERROR: Work directory ${workDir:?} does not exist"
            exit 1
          fi
        fi
      fi
    fi
