---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: skip-trusted-artifact-operations
spec:
  description: >-
    This stepaction creates the file .skip-trusted-artifacts if the param ociStorage is
    "empty".
  image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
  params:
    - name: ociStorage
      type: string
      default: "empty"
    - name: workDir
      type: string
      default: "/workspace/data"
  env:
    - name: ociStorage
      value: $(params.ociStorage)
    - name: workDir
      value: $(params.workDir)
  script: |
    #!/usr/bin/env bash
    set -eo pipefail
    
    if [ "${ociStorage:?}" == "empty" ]; then
      echo "oci storage not detected via ociStorage...skipping trusted artifacts tasks"
      mkdir -p "${workDir:?}"
      touch "${workDir:?}/.skip-trusted-artifacts"
    fi
