apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: patch-source-data-artifact-result
spec:
  image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
  params:
    - name: ociStorage
      type: string
      default: "empty"
    - name: sourceDataArtifact
      type: string
      default: ""
  env:
  - name: ociStorage
    value: $(params.ociStorage)
  - name: sourceDataArtifact
    value: $(params.sourceDataArtifact)
  script: |
    #!/usr/bin/env bash
    set -eo pipefail
    
    # this is needed to skip trusted-artifacts tasks
    # when using PVC based workspaces.
    if [ "${ociStorage}" == "empty" ]; then
      echo -n "${ociStorage}" > "${sourceDataArtifact}"
    fi
