---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: create-advisory-oci-artifact
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: advisory
spec:
  description: >-
      Pipeline to generate an oci artifact containing an advisory json using an advisory url.
  params:
    - name: advisory_url
      type: string
      description: advisory url
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/release-service-catalog.git
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
  tasks:
    - name: create-advisory-oci-artifact
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/create-advisory-oci-artifact-task/create-advisory-oci-artifact-task.yaml
      params:
        - name: advisory_url
          value: $(params.advisory_url)
        - name: internalRequestPipelineRunName
          value: $(context.pipelineRun.name)
  results:
    - name: result
      value: $(tasks.create-advisory-oci-artifact.results.result)
    - name: advisory_oci_artifact
      value: $(tasks.create-advisory-oci-artifact.results.advisory_oci_artifact)
    - name: internalRequestPipelineRunName
      value: $(tasks.create-advisory-oci-artifact.results.internalRequestPipelineRunName)
    - name: internalRequestTaskRunName
      value: $(tasks.create-advisory-oci-artifact.results.internalRequestTaskRunName)
