---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  data:
    atlas:
      server: stage
      atlas-sso-secret-name: atlas-staging-sso-secret-${component_name}
      atlas-retry-aws-secret-name: atlas-retry-s3-staging-secret-${component_name}
    pyxis:
      server: stage
      secret: pyxis-${component_name}
    sign:
      configMapName: "hacbs-signing-pipeline-config-redhatbeta2"
      cosignSecretName: "konflux-cosign-signing-stage-${component_name}"
    mapping:
      defaults:
        tags:
          - latest
        pushSourceContainer: true
      components:
        - name: ${component_name}
          repository: quay.io/redhat-pending/rhtap----rh-advisories-component
    releaseNotes:
      product_id:
        - 999
      product_name: Red Hat Comp2
      product_version: '1.0.1'
      cpe: 'cpe:/a:redhat:comp2:1::appstream'
      product_stream: comp2-1.0
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/rh-advisories/rh-advisories.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
