---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: managed-release-pipeline-resource-role-binding-for-${managed_sa_name}
  labels:
    originating-tool: "${originating_tool}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
  - kind: ServiceAccount
    name: ${managed_sa_name}
    namespace: ${managed_namespace}
