---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${managed_sa_name}
  labels:
    originating-tool: "${originating_tool}"
secrets:
  - name: konflux-ci-konflux-release-trusted-artifacts-pull-secret-${component_name}
  - name: pulp-credentials-${component_name}
imagePullSecrets:
  - name: konflux-ci-konflux-release-trusted-artifacts-pull-secret-${component_name}
  - name: pulp-credentials-${component_name}
