---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: reduce-snapshot
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to reduce snapshot
  params:
    - name: IMAGES
      type: string
    - name: SINGLE_COMPONENT
      type: string
    - name: CR_TO_QUERY
      type: string
    - name: CR_TO_QUERY_NAMESPACE
      type: string
    - name: SNAPSHOT_PATH
      type: string
  workspaces:
    - name: data
      description: Workspace to save the CR jsons to
  steps:
    - name: reduce
      params:
        - name: IMAGES
          value: $(params.IMAGES)
        - name: SINGLE_COMPONENT
          value: $(params.SINGLE_COMPONENT)
        - name: CR_TO_QUERY
          value: $(params.CR_TO_QUERY)
        - name: CR_TO_QUERY_NAMESPACE
          value: $(params.CR_TO_QUERY_NAMESPACE)
        - name: SNAPSHOT_PATH
          value: $(params.SNAPSHOT_PATH)
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/scoheb/release-service-catalog
          - name: revision
            value: single-component-mode-reduce-snapshot-json
          - name: pathInRepo
            value: stepactions/reduce-snapshot/reduce-snapshot.yaml
