---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    originating-tool: "${originating_tool}"
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
    release.appstudio.openshift.io/releasePlanAdmission: "${release_plan_admission_name}"
  name: ${release_plan_name}
spec:
  application: ${application_name}
  target: ${managed_namespace}
