---
name: Promote branch
on:
  workflow_dispatch:
    inputs:
      promotion-type:
        description: The type of promotion to perform
        type: choice
        required: true
        default: development-to-staging
        options:
          - development-to-staging
          - staging-to-production
      force-to-staging:
        description: |
          Force to staging: Allow promotion to staging even if staging and production differ
        type: boolean
        required: true
        default: false
      override:
        description: |
          Override: Allow promotion to production even if the change has not been in staging for one
          week
        type: boolean
        required: true
        default: false
      dry-run:
        description: |
          Dry run: Print out the changes that would be promoted but do not perform the git push
        type: boolean
        required: true
        default: false
jobs:
  promote-branch:
    name: Promote Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run branch promotion script
        run: |
          .github/scripts/promote_branch.sh --promotion-type $PROMOTION_TYPE --force-to-staging $FORCE \
            --override $OVERRIDE --dry-run $DRY
        env:
          PROMOTION_TYPE: ${{ inputs.promotion-type }}
          FORCE: ${{ inputs.force-to-staging }}
          OVERRIDE: ${{ inputs.override }}
          DRY: ${{ inputs.dry-run }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
